config/routes.rb
Rails.application.routes.draw do
  resources :sql_metrics, :only => [:index, :destroy]
end

app/models/ew_sql_metrics/metric.rb
module EwSqlMetrics
  class Metric
    include Mongoid::Document
    
    field :name, :type => String
    field :duration, :type => Integer
    field :instrumenter_id, :type => String
    field :payload, :type => Hash
    field :started_at, :type => Time
    field :created_at, :type => Time
    field :user_id, :type => Integer
    field :user_email, :type => String
    
    def self.store!(args)
      metric = new
      metric.parse(args)
      metric.save!
    end

    def parse(args)
      self.name            = args[0]
      self.started_at      = args[1]
      self.duration        = (args[2] - args[1]) * 1000000
      self.instrumenter_id = args[3]
      self.payload         = args[4]
      self.created_at      = Time.now.utc
      self.user_id         = args[5]
      self.user_email      = args[6]
    end
  end
end

app/controllers/sql_metrics_controller.rb
class SqlMetricsController < ApplicationController
  before_filter :check_auth
  
  def index
    @metrics = EwSqlMetrics::Metric.all(:conditions =>
     { :user_email => current_user.email }).descending(:created_at).paginate(:page => params[:page])
  end
  
  def destroy
    @metric = EwSqlMetrics::Metric.find(params[:id])
    @metric.destroy
    redirect_to sql_metrics_url
  end
  
  private
  
  def check_auth
    request.env["warden"].authenticate!
  end
  
end

app/views/sql_metrics/index.html.erb
<h1>Listing SQL Metrics</h1>

<p>All sql queries made by <%= current_user.email %></p>
<table cellspacing="10">
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Started at</th>
    <th>Payload</th>	
    <th></th>
	
  </tr>

<% @metrics.each do |metric| %>
  <tr>
    <td><%= metric.name %></td>
    <td><%= metric.duration %> ms</td>
    <td>
	  <%= time_ago_in_words metric.started_at %> ago
	  <%= metric.started_at.strftime("%d %m %Y %H:%M") %>
	</td>
    <td>
      <% metric.payload.each do |k, v| %>
        <p><b><%= k.humanize %></b><br /> <%= v %></p>
      <% end %>
    </td>
	
    <td><%= link_to 'Destroy', sql_metric_path(metric),
      :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @metrics %>